import json
from datetime import datetime, timedelta
from pathlib import Path
import sys

def rewrite():
    code = '''"""
Yellow Rose BBQ - Polars & Plotly Interactive Forecasting Engine
Generates high-performance time-series predictions using the SARIMA baseline (category_payload.json).
Outputs Plotly-compatible interactive JSON structures for the dashboard.
"""

import json
from datetime import datetime, timedelta
from pathlib import Path
from typing import Dict, Any
import sys

# Ensure clover_api is in path
sys.path.append(str(Path(__file__).parent.parent.parent))

from clover_api.secure_config import DB_PATH, ANALYTICS_DIR

def load_arima_forecast() -> Dict[str, Any]:
    """Loads the category_payload.json generated by arima_baseline.py"""
    payload_path = ANALYTICS_DIR / "category_payload.json"
    if not payload_path.exists():
        print(f"[ERROR] {payload_path} not found. Run arima_baseline.py first.")
        return None
    with open(payload_path, 'r') as f:
        return json.load(f)

def generate_forecast_data_polars(days: int = 14) -> Dict[str, Any]:
    """
    Reads the ARIMA forecast for the next 14 days and constructs the dashboard payload.
    """
    arima_data = load_arima_forecast()
    if not arima_data:
        raise ValueError("Missing ARIMA forecast data.")

    future_dates = arima_data["forecast_metrics"]["future_dates"][:days]
    categories = arima_data["forecast_metrics"]["categories"]
    
    # We will map the dates back to objects
    records = []
    
    for i in range(len(future_dates)):
        # future_dates looks like "2026-08-12 (Wed)"
        date_str, day_name = future_dates[i].split(" (")
        day_name = day_name.replace(")", "")
        
        brisket_pure_raw_lbs = categories.get("brisket_lbs", {}).get("forecast", [0]*30)[i]
        pork_pure_raw_lbs = categories.get("pulled_pork_lbs", {}).get("forecast", [0]*30)[i]
        sausage_lbs = categories.get("sausage_links", {}).get("forecast", [0]*30)[i]
        tacos_brisket = categories.get("tacos_brisket", {}).get("forecast", [0]*30)[i]
        tacos_pork = categories.get("tacos_pork", {}).get("forecast", [0]*30)[i]
        tacos_sold = tacos_brisket + tacos_pork
        rosebuds_sold = categories.get("rosebuds", {}).get("forecast", [0]*30)[i]
        pork_ribs_racks = categories.get("pork_ribs_racks", {}).get("forecast", [0]*30)[i]
        beef_dino_ribs = categories.get("beef_dino_ribs", {}).get("forecast", [0]*30)[i]
        
        # Calculate raw meat needed for composed items (Yield Loss = 50%)
        # 1 Taco = 0.25 lbs cooked meat = 0.5 lbs raw meat
        # 1 Rosebud = 0.1 lbs cooked meat = 0.2 lbs raw meat
        brisket_raw_tacos = tacos_brisket * 0.5
        brisket_raw_rosebuds = rosebuds_sold * 0.2
        pork_raw_tacos = tacos_pork * 0.5
        
        brisket_raw_lbs = brisket_pure_raw_lbs + brisket_raw_tacos + brisket_raw_rosebuds
        pork_lbs = pork_pure_raw_lbs + pork_raw_tacos
        
        # We need to compute predicted_revenue and staffing. We can estimate revenue from the demand index.
        demand_index = arima_data["forecast_metrics"]["demand_index"]["future"][:days][i]
        base_revenue = 1800.0 * demand_index
        
        staff_count = min(5, max(2, int(base_revenue // 800) + 1))
        pit_hours = round(staff_count * 8.5, 1)

        records.append({
            "date": date_str,
            "day_name": day_name,
            "predicted_revenue": round(base_revenue, 2),
            "brisket_raw_lbs": round(brisket_raw_lbs, 1),
            "pork_shoulder_raw_lbs": round(pork_lbs, 1),
            "sausage_lbs": round(sausage_lbs, 1),
            "tacos_sold": int(tacos_sold),
            "rosebuds_sold": int(rosebuds_sold),
            "pork_ribs_racks": int(pork_ribs_racks),
            "beef_dino_ribs": int(beef_dino_ribs),
            "recommended_staff": staff_count,
            "pitmaster_hours": pit_hours
        })

    # Generate dynamic insight string
    saturday_record = next((r for r in records if r["day_name"] == "Sat"), records[0])
    insight_string = (
        f"Because brisket loses 50% of its weight during the 14-hour smoke, and composed items like "
        f"Tacos ({int(saturday_record['tacos_sold'])} projected) and Rosebuds ({int(saturday_record['rosebuds_sold'])} projected) "
        f"pull directly from this yield, the {saturday_record['brisket_raw_lbs']} lbs of total raw brisket accounts for both pure meat sales and composed items."
    )

    return {
        "generated_at": datetime.now().isoformat(),
        "days_count": days,
        "insight_string": insight_string,
        "forecast_records": records
    }

def build_plotly_meat_chart_json(forecast_data: Dict[str, Any]) -> str:
    """Generates JSON payload for Plotly interactive line/bar chart."""
    records = forecast_data["forecast_records"]
    dates = [r["date"] + f" ({r['day_name']})" for r in records]
    brisket = [r["brisket_raw_lbs"] for r in records]
    pork = [r["pork_shoulder_raw_lbs"] for r in records]
    sausage = [r["sausage_lbs"] for r in records]
    tacos = [r["tacos_sold"] for r in records]
    rosebuds = [r["rosebuds_sold"] for r in records]
    pork_ribs = [r["pork_ribs_racks"] for r in records]
    beef_ribs = [r["beef_dino_ribs"] for r in records]

    fig_data = [
        {
            "x": dates,
            "y": brisket,
            "name": "Raw Brisket Prep (lbs)",
            "type": "bar",
            "marker": {"color": "#c0392b"}
        },
        {
            "x": dates,
            "y": pork,
            "name": "Pork Shoulder (lbs)",
            "type": "bar",
            "marker": {"color": "#e67e22"}
        },
        {
            "x": dates,
            "y": sausage,
            "name": "Sausage Sold (lbs)",
            "type": "scatter",
            "mode": "lines+markers",
            "yaxis": "y2",
            "line": {"color": "#f1c40f", "width": 3},
            "marker": {"size": 8}
        },
        {
            "x": dates,
            "y": tacos,
            "name": "Tacos Sold",
            "type": "scatter",
            "mode": "lines",
            "yaxis": "y2",
            "line": {"color": "#27ae60", "width": 2, "dash": "dot"}
        },
        {
            "x": dates,
            "y": rosebuds,
            "name": "Rosebuds Sold",
            "type": "scatter",
            "mode": "lines",
            "yaxis": "y2",
            "line": {"color": "#8e44ad", "width": 2, "dash": "dot"}
        },
        {
            "x": dates,
            "y": pork_ribs,
            "name": "Pork Ribs (Racks)",
            "type": "scatter",
            "mode": "lines+markers",
            "yaxis": "y2",
            "line": {"color": "#d35400", "width": 2}
        },
        {
            "x": dates,
            "y": beef_ribs,
            "name": "Beef Dino Ribs",
            "type": "scatter",
            "mode": "lines+markers",
            "yaxis": "y2",
            "line": {"color": "#7f8c8d", "width": 2}
        }
    ]

    fig_layout = {
        "title": "14-Day Predicted Meat Production & Composed Item Sales",
        "paper_bgcolor": "rgba(0,0,0,0)",
        "plot_bgcolor": "rgba(20,20,30,0.6)",
        "font": {"color": "#f8fafc", "family": "Outfit, sans-serif"},
        "xaxis": {"gridcolor": "rgba(255,255,255,0.1)", "tickangle": 45},
        "yaxis": {"title": "Raw Meat Weight (lbs)", "gridcolor": "rgba(255,255,255,0.1)"},
        "yaxis2": {
            "title": "Composed Items / Units",
            "overlaying": "y",
            "side": "right",
            "showgrid": False,
            "titlefont": {"color": "#f1c40f"},
            "tickfont": {"color": "#f1c40f"}
        },
        "legend": {"orientation": "h", "y": -0.35, "x": 0},
        "margin": {"l": 60, "r": 60, "t": 60, "b": 110}
    }

    return json.dumps({"data": fig_data, "layout": fig_layout})

def export_dashboard_data():
    """Exports pre-rendered interactive dashboard data to JSON artifact."""
    forecast = generate_forecast_data_polars()
    chart_json = build_plotly_meat_chart_json(forecast)
    
    out_file = ANALYTICS_DIR / "dashboard_payload.json"
    with open(out_file, "w") as f:
        json.dump({"forecast": forecast, "plotly_meat_chart": json.loads(chart_json)}, f, indent=2)
    print(f"[DASHBOARD] Saved interactive forecasting payload to {out_file}")

if __name__ == "__main__":
    try:
        export_dashboard_data()
    except Exception as e:
        import traceback
        import sys
        print(f"[FATAL ERROR] Pipeline failed: {e}")
        traceback.print_exc()
        sys.exit(1)
'''
    with open('clover_api/analytics/dashboard.py', 'w') as f:
        f.write(code)

if __name__ == "__main__":
    rewrite()
